name: Keep Hugging Face Space Alive
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Real User Visit
        run: |
          echo "جاري إيقاظ فضاء Hugging Face بأمان..."
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -o /dev/null \
            https://huggingface.co/spaces/kiyunhai/s
          echo "تمت زيارة الفضاء بنجاح والخادم مستيقظ الآن!"
